# Generated by Django 2.0.7 on 2019-01-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(db_column='adminID', primary_key=True, serialize=False)),
                ('adminuser', models.CharField(db_column='adminUser', max_length=45)),
                ('adminpass', models.CharField(db_column='adminPass', max_length=45)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('medname', models.CharField(blank=True, db_column='medName', max_length=45, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('presentcount', models.IntegerField(blank=True, db_column='presentCount', null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=43, primary_key=True, serialize=False)),
                ('fn', models.CharField(blank=True, max_length=45, null=True)),
                ('ln', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
